/**
 *
 * $Id$
 */
package org.lunifera.mobile.vaadin.ecview.model.validation;

import org.eclipse.emf.ecp.ecview.common.model.binding.YECViewModelValueBindingEndpoint;

import org.lunifera.mobile.vaadin.ecview.model.VMNavigationHandler;
import org.lunifera.mobile.vaadin.ecview.model.VMNavigationPage;

/**
 * A sample validator interface for {@link org.lunifera.mobile.vaadin.ecview.model.VMNavigationCommand}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VMNavigationCommandValidator {
	boolean validate();

	boolean validateTargetPage(VMNavigationPage value);
	boolean validateValue(Object value);

	boolean validateNavigationHandler(VMNavigationHandler value);
	boolean validateNavigationValueEndpoint(YECViewModelValueBindingEndpoint value);
}
