/**
 *
 * $Id$
 */
package org.lunifera.mobile.vaadin.ecview.model.validation;

import org.eclipse.emf.ecp.ecview.common.model.datatypes.YDatadescription;
import org.lunifera.mobile.vaadin.ecview.model.VMNavigationPage;

/**
 * A sample validator interface for {@link org.lunifera.mobile.vaadin.ecview.model.VMNavigationButton}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VMNavigationButtonValidator {
	boolean validate();

	boolean validatePage(VMNavigationPage value);
	boolean validatePageAlias(VMNavigationPage value);

	boolean validateDatadescription(YDatadescription value);
}
