/**
 *
 * $Id$
 */
package org.lunifera.mobile.vaadin.ecview.model.validation;


/**
 * A sample validator interface for {@link org.lunifera.mobile.vaadin.ecview.model.VMNavigationPage}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VMNavigationPageValidator {
	boolean validate();

	boolean validateType(Class<?> value);

	boolean validateEmfNsURI(String value);

	boolean validateTypeQualifiedName(String value);

	boolean validateValue(Object value);

}
