/**
 *
 * $Id$
 */
package org.lunifera.mobile.vaadin.ecview.model.validation;

import org.eclipse.emf.ecp.ecview.common.model.core.YEmbeddable;

import org.eclipse.emf.ecp.ecview.common.model.datatypes.YDatadescription;

import org.lunifera.mobile.vaadin.ecview.model.VMTabSheet;

/**
 * A sample validator interface for {@link org.lunifera.mobile.vaadin.ecview.model.VMTab}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VMTabValidator {
	boolean validate();

	boolean validateParent(VMTabSheet value);
	boolean validateEmbeddable(YEmbeddable value);
	boolean validateDatadescription(YDatadescription value);
}
